auto: false
auto: true
server: false
lsi: false
pygments: true
permalink: /:title
paginate: 10
exclude: ["Rakefile", "LICENSE.txt", "CNAME"]
title: UnitGS Demo
url: http://demo.unitgs.bernardoantunes.com
github_user: bernardoantunes